package com.cofaktory.footprint.model;

public class ReductionStrategy {
    private int reductionId;
    private int branchId;
    private int userId;
    private String reductionStrategy;
    private int statusId;
    private double implementationCosts;
    private double projectedAnnualProfits;

    // Full constructor (including projectedAnnualProfits, for SELECTs)
    public ReductionStrategy(int reductionId, int branchId, int userId, String reductionStrategy,
                             int statusId, double implementationCosts, double projectedAnnualProfits) {
        this.reductionId = reductionId;
        this.branchId = branchId;
        this.userId = userId;
        this.reductionStrategy = reductionStrategy;
        this.statusId = statusId;
        this.implementationCosts = implementationCosts;
        this.projectedAnnualProfits = projectedAnnualProfits;
    }

    // Constructor for INSERT/UPDATE (projectedAnnualProfits is generated by DB)
    public ReductionStrategy(int reductionId, int branchId, int userId, String reductionStrategy,
                             int statusId, double implementationCosts) {
        this(reductionId, branchId, userId, reductionStrategy, statusId, implementationCosts, 0.0);
    }

    public ReductionStrategy() {}

    public int getReductionId() {
        return reductionId;
    }

    public void setReductionId(int reductionId) {
        this.reductionId = reductionId;
    }

    public int getBranchId() {
        return branchId;
    }

    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getReductionStrategy() {
        return reductionStrategy;
    }

    public void setReductionStrategy(String reductionStrategy) {
        this.reductionStrategy = reductionStrategy;
    }

    public int getStatusId() {
        return statusId;
    }

    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    public double getImplementationCosts() {
        return implementationCosts;
    }

    public void setImplementationCosts(double implementationCosts) {
        this.implementationCosts = implementationCosts;
    }

    public double getProjectedAnnualProfits() {
        return projectedAnnualProfits;
    }

    public void setProjectedAnnualProfits(double projectedAnnualProfits) {
        this.projectedAnnualProfits = projectedAnnualProfits;
    }
}